### PR TITLE
Extend cmake to generate find module and optionally build shared lib

### PR DESCRIPTION
**Pull request by wdobbe**
1) After 'make install' you can use the jwt-cpp library in another CMake project as follows:

find_package(Jwt "1.1.0" REQUIRED)
add_executable(foo foo.cpp)
target_link_libraries(foo Jwt::jwt)

If jwt-cpp has been installed in a non-standard location than you will have to include the install path in CMAKE_PREFIX_PATH.

2) When you add option -DBUILD_SHARED_LIBS=ON to the CMake invocation, jwt-cpp will be built as a shared library.

Question: is there a reason that jwt-cpp searches for OpenSSL with custom commands i.s.o. using the standard CMake find module FindOpenSSL.cmake ?

best regards,
Winfried

### CODE REVIEW

**Comment by wdobbe** [comment]
Correction to the pull-request comment:

If jwt-cpp has been installed in a non-standard location than you will have to include the install path in CMAKE_PREFIX_PATH.

**Comment by pokowaka** [comment]
Is it possible to lower the required cmake version? It breaks the integration

**Comment by wdobbe** [comment]
Yes, it will probably work from CMake 3.0 and maybe even with the last release of the 2.x cycle. However I don't have such old came versions installed and thus was not able to test with cmake < 3.4.

In the integration build log I see you use cmake 3.2.2. I will download that release from cmake.org and check that this change will work with it.

**Comment by wdobbe** [comment]
After testing I have changed the minimum cmake version to 3.2

**Comment by pokowaka** [comment]
Thank you!

**Pull request merged**
